#!/bin/bash
# Check that modified files meet style requirements 
# Place in .git/hooks

ASTYLE_ARGS="--style=allman --add-brackets --indent=tab --lineend=linux"

ASTYLE=$(which astyle 2> /dev/null )
if [ $? -ne 0 ]; then
	echo "AStyle not found."
	echo "Please install it from your package manager or http://astyle.sourceforge.net/."
	echo "Or bypass check with 'git commit --no-verify'"
	exit 1
fi

FILES=`git diff --cached --name-only --diff-filter=ACMR | grep -E "\.(cpp|h)$"`
BAD_FILES=""

for FILE in $FILES;
do
	if ! $ASTYLE $ASTYLE_ARGS < $FILE | cmp -s $FILE -
	then 
		echo $FILE "failed style check"
		BAD_FILES="$BAD_FILES $FILE"
	fi
done

if [ -n "$BAD_FILES" ]
then
	echo "Please run:"
	echo "astyle --suffix=none" $ASTYLE_ARGS $BAD_FILES
	echo "Or bypass check with 'git commit --no-verify'"
	exit 1
fi


