#!/bin/bash
# Check that modified files meet style requirements 
# Place in .git/hooks


STYLE_SCRIPT="tools/style_wrapper.py"

FILES=`git diff --cached --name-only --diff-filter=ACMR | grep -E "\.(cpp|h)$"`
BAD_FILES=""

for FILE in $FILES;
do
	if ! $STYLE_SCRIPT check $FILE
	then 
		echo $FILE "failed style check"
		BAD_FILES="$BAD_FILES $FILE"
	fi
done

if [ -n "$BAD_FILES" ]
then
	echo "To see require changes run:"
	echo $STYLE_SCRIPT diff $BAD_FILES
	echo "To fix:"
	echo $STYLE_SCRIPT fix $BAD_FILES
	echo git add $BAD_FILES
	echo "Or bypass check with 'git commit --no-verify'"
	exit 1
fi

